// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdsbggqczqfvkhhskvkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkc2JnZ3FjenFmdmtoaHNrdmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzQ1MTksImV4cCI6MjA2NTc1MDUxOX0.SUxhhbZnbCQBQs-aidpYnGIwWVVz3G5pi8eiQxu-kYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);